#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FILE=$1
OUT=$SCRIPTDIR/$2

pandoc $FILE --wrap=none --from=html-raw_html --to=markdown-raw_html-header_attributes+tex_math_dollars-definition_lists --atx-headers  -o $OUT

# Make sure block quotes have a space for empty lines
sed -i 's/^>$/> /g' $OUT

# Remove special classes on backticks and links
sed -i 's/{\.docutils \.literal}//g' $OUT
sed -i 's/{\.reference \.external}//g' $OUT
sed -i 's/{\.toc-backref}//g' $OUT

# Set the code block headers reasonably
sed -i 's/{\.doctest-block}/{\.python}/g' $OUT

sed -i 's/\s*{\.literal-block}\s*//g' $OUT

# Remove the autogenerated table of contents and add a TOC widget
tail -n +$(grep -n -m 1 '^#' $OUT | sed  's/\([0-9]*\).*/\1/') $OUT > tmp.md
cp tmp.md $OUT
sed -i.old '1s;^;\n[[table-of-contents]]\n\n;' $OUT

# Remove links from headers
perl -i -pe 's/^(#+) \[([\d\.]+)[^\x00-\x7F]*(.+)\]\(.*\)/\1 \2 \3/g' $OUT

# Fix up code blocks
./deindent_codeblocks.py $OUT $OUT

# Fix up math (convert to dollar signs and un-escape stuff)
./fixup_math.py $OUT $OUT

# Make sure MathJax block maths are on their own lines
# perl -i -pe 'BEGIN {undef $/;} s/(\$\$[^\$]+\$\$)/\n\n$1\n\n/sgm' $OUT
perl -i -pe 'BEGIN {undef $/;} s/(\$\$[^\$]+\$\$)/\n\n$1\n\n/sgm' $OUT
# We might have over-spaced, some, so fix this
# Remove extra newlines at the end
perl -i -pe 'BEGIN {undef $/;} s/(\$\$[^\$]+\$\$)\n\n\n\n/$1\n\n/sgm' $OUT
perl -i -pe 'BEGIN {undef $/;} s/(\$\$[^\$]+\$\$)\n\n\n/$1\n\n/sgm' $OUT
# Remove extra newlines at the beginning
perl -i -pe 'BEGIN {undef $/;} s/\n\n\n\n(\$\$[^\$]+\$\$)/\n\n$1/sgm' $OUT
perl -i -pe 'BEGIN {undef $/;} s/\n\n\n(\$\$[^\$]+\$\$)/\n\n$1/sgm' $OUT


# Split into sub-sections
chapter=$(echo $FILE | sed -rn 's/[^[:digit:]]*([[:digit:]]+)[^[:digit:]]*/\1/p')
base=$(echo $OUT | cut -f 1 -d '.')
i="1"
cp $OUT ${base}.${i}.md;
number_re='^[0-9]+$'
while true; do
    offset=$(cat ${base}.${i}.md | grep "# $chapter.$[$i+1]" -m 1 -b | sed 's/:.*//')

    if ! [[ $offset =~ $number_re ]] ; then
        break
    fi

    echo "" > ${base}.$[$i+1].md
    echo "[[table-of-contents]]" >> ${base}.$[$i+1].md
    cat ${base}.${i}.md | tail -c +$offset >> ${base}.$[$i+1].md
    cat ${base}.${i}.md | head -c +$offset > tmp.md
    cp tmp.md ${base}.${i}.md

    i=$[$i+1]
done
rm $OUT
rm -f $OUT.old
