#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FILE=$1
OUT=$SCRIPTDIR/$2

pandoc $FILE --wrap=none --from=html-raw_html --to=markdown-raw_html-header_attributes+tex_math_dollars --atx-headers  -o $OUT

# Make sure block quotes have a space for empty lines
sed -i 's/^>$/> /g' $OUT

# Remove special classes on backticks and links
sed -i 's/{\.docutils \.literal}//g' $OUT
sed -i 's/{\.reference \.external}//g' $OUT
sed -i 's/{\.toc-backref}//g' $OUT

# Set the code block headers reasonably
sed -i 's/{\.doctest-block}/{\.python}/g' $OUT

sed -i 's/{\.literal-block}/{}/g' $OUT

# Remove the autogenerated table of contents and add a TOC widget
tail -n +$(grep -n -m 1 '^#' $OUT | sed  's/\([0-9]*\).*/\1/') $OUT > tmp.md
cp tmp.md $OUT
sed -i.old '1s;^;\n[[table-of-contents]]\n\n;' $OUT

# Remove links from headers
perl -i -pe 's/^(#+) \[([\d\.]+)[^\x00-\x7F]*(.+)\]\(.*\)/\1 \2 \3/g' $OUT

# Fix up maths
perl -i -pe 's/\\\\\(/\$/g' $OUT
perl -i -pe 's/\\\\\)/\$/g' $OUT
perl -i -pe 's/\\\\\\\[/\$\$/g' $OUT
perl -i -pe 's/\\\\\\\]/\$\$\n/g' $OUT
